import type { Challenge } from '../types';

export const challenges: Challenge[] = [
  // Node 0: Onboarding - Meet Max & Spark (5-Beat structure)
  {
    id: 'onboarding',
    number: 0,
    type: 'onboarding',
    path: '',
    title: 'Meet Max & Spark',
    duration: '2 min',
    preScript: "Hey! I'm Max, your math tutor. I love teaching math — especially when it involves pizza and puzzles!",
    postQuestion: '',
    contextInfo: 'Onboarding warm-up conversation. No assessment.',
    maxTurns: 5,
  },
  // Node 1: Slide 1 — Why Fractions? (motivation hook)
  {
    id: 'slide-1',
    number: 1,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-1-why-fractions.png',
    title: 'Why Fractions?',
    duration: '1 min',
    preScript: "You know how sometimes you share food with friends? There's actually math behind fair sharing — and that's what we're learning today! Take a look.",
    slideNarration: '',  // Removed — slide visual already shows this info; preScript covers the intro
    postQuestion: '',
    contextInfo: 'Motivation slide showing why we learn fractions - sharing cake with friends.',
    correctnessFilter: '',
    scaffolding: {
      probe1: '',
      probe2: '',
      hint: '',
      scaffold: '',
      reveal: ''
    },
    maxTurns: 0,
    isQuestionSlide: false,
    minionMoment: {
      minionLine: "Wait wait wait... fractions? Is that like... fracturing a bone?!",
      tutorLine: "Ha! Not quite, Spark. But it IS about breaking things into pieces! Let's find out.",
    },
    microConversation: {
      type: 'curiosity',
      position: 'after_narration',
      prompt: "Before we jump in — what do you think a fraction is? Just guess!",
      context: "Opening slide about fractions. Student hasn't learned anything yet — this is a pure prediction to spark curiosity.",
      transitionTo: "The next video will show fractions in everyday life (pizza, chocolate bars).",
      fallback: "Love that you're thinking about it! Let's find out together!",
    },
  },
  // Node 2: Video 1 — What are Fractions?
  {
    id: 'video-1',
    number: 2,
    type: 'video',
    path: '/fractions-module-content/videos/video-1.mp4',
    youtubeId: 'kD3wbmePp_8',
    title: 'What are Fractions?',
    duration: '2.5 min',
    preScript: '',  // Removed — micro-conversation prompt serves as the intro before the video
    postQuestion: "You just learned that fractions have special names. If a pizza is cut into 4 equal slices, what is the fraction name for ONE slice?",
    contextInfo: "This video teaches basic fraction concepts using pizza and cake examples. Kids learn that fractions are parts of a whole.",
    correctnessFilter: "one fourth|quarter|1/4|one-fourth|a fourth",
    dynamicSlideTemplate: 'fraction-builder',
    dynamicSlideId: 'node-2-pizza-slice',
    wrapUp: "You named your first fraction — one-fourth! Pizza math is just the beginning!",
    scaffolding: {
      probe1: "Fractions have special names! When there are 4 equal pieces, what's the fraction name for just ONE piece?",
      probe2: "Think about the number FOUR. Each piece is called a 'fourth'. So what do we call ONE of them?",
      hint: "Think about it — one piece, out of four. Put those together!",
      reveal: "It's one-fourth! Or you can say 'one quarter'. That's the special fraction name. Great job!"
    },
    maxTurns: 4,
  },
  // Node 3: Applet A1 — Cut and Glue Practice
  {
    id: 'applet-a1',
    number: 3,
    type: 'applet',
    path: '/fractions-module-content/applets/A1. M2-Fraction Cut and Glue Practice/index.html',
    title: 'Cut and Glue Practice',
    duration: '4 min',
    preScript: "In the video, you saw fractions need equal parts. Now it's your turn — cut this paper into pieces that are all the same size!",
    postQuestion: "When we make fractions, what do we need to remember about the size of the pieces?",
    contextInfo: "Interactive paper cutting activity. Kids practice making equal parts (halves, quarters). They use virtual scissors and glue.",
    correctnessFilter: "equal|same size|equal size",
    dynamicSlideTemplate: 'tap-to-select',
    dynamicSlideId: 'node-3-fair-share',
    wrapUp: "Equal parts — that's the secret to fractions! Let's keep building.",
    scaffolding: {
      probe1: "If you share a chocolate bar with your friend, would it be fair if one piece is big and one tiny?",
      probe2: "When we share equally, what must be true about each piece?",
      hint: "For fair sharing, pieces must be what kind of size?",
      scaffold: "Think about the word 'same' - same size means equal!",
      reveal: "Same size! For fractions, all pieces must be equal - same size. Nice effort!"
    },
    maxTurns: 5,
    minionMoment: {
      minionLine: "I cut my paper into pieces but they're all different sizes! That counts, right?",
      tutorLine: "Hmm, actually no! Remember — fractions need equal parts. All pieces must be the same size!",
    },
  },
  // Node 4: Checkpoint LO1 — Equal Parts Basics
  {
    id: 'checkpoint-lo1',
    number: 4,
    type: 'checkpoint',
    path: '',
    title: 'Level Up: Equal Parts!',
    duration: '2 min',
    preScript: "Amazing! You already know that fractions are about equal parts, and you can name them too! Let's do a quick check!",
    postQuestion: "If you cut a cake into 2 equal pieces, what do we call each piece?",
    contextInfo: 'Checkpoint reviewing LO1: fractions = equal parts, basic naming (one-half, one-fourth).',
    isCheckpoint: true,
    checkpointLO: 'LO1: Understanding equal parts and first fraction names',
    checkpointId: 'lo1',
    maxTurns: 4,
    correctnessFilter: 'half|one half|1/2|one-half|a half',
    scaffolding: {
      probe1: "You have 2 equal pieces. Each piece is one out of two. What's the fraction name?",
      probe2: "Think about the number TWO. Each piece is a...",
      hint: "One piece out of two — put those together!",
      reveal: "It's one-half! Each piece is 1/2. You levelled up!"
    },
  },
  // Node 5: Applet A2 — Fraction Patterns
  {
    id: 'applet-a2',
    number: 5,
    type: 'applet',
    path: '/fractions-module-content/applets/A2.M2-Fraction Paper Cut Snapshot/index.html',
    title: 'Fraction Patterns',
    duration: '2 min',
    preScript: "You've been cutting things into equal parts — nice! But what happens when you cut into MORE pieces? Watch what happens to the SIZE of each piece.",
    postQuestion: "Which has MORE pieces - 1/4 or 1/6?",
    contextInfo: "Visual comparison of fractions 1/2, 1/4, 1/6. Correct answer: 1/6 has more pieces (6 pieces vs 4 pieces).",
    correctnessFilter: "1/6|one sixth|six|1 6",
    scaffolding: {
      probe1: "If you cut a cake into 4 slices vs 6 slices, which way makes more pieces?",
      probe2: "Look at the bottom numbers - 4 and 6. Which number is bigger?",
      hint: "More cuts = more pieces. Does 1/4 or 1/6 have more cuts?",
      scaffold: "6 is bigger than 4. So which fraction has more pieces - 1/4 or 1/6?",
      reveal: "1/6 has more pieces! 6 is more than 4. Good thinking!"
    },
    maxTurns: 5,
    hasDynamicSlide: true  // Uses interactive FractionCompareSlide for post-challenge
  },
  // Node 6: Goofy Moment 1 — Spark's Fraction Joke
  {
    id: 'goofy-1',
    number: 6,
    type: 'goofy',
    path: '',
    title: 'Spark\'s Fraction Joke',
    duration: '30 sec',
    preScript: '',
    postQuestion: '',
    contextInfo: 'Fun break - goofy moment with Spark.',
    maxTurns: 0,
    goofyScript: {
      tutorLine: "Hey Spark, do you know what a fraction is?",
      minionLine: "I tried to eat 5/4 of a cake once... it didn't end well! My tummy hurt for DAYS!",
      showMinion: true,
    },
    microConversation: {
      type: 'reaction',
      position: 'after_goofy',
      prompt: "Ha! Poor Spark ate way too much pizza! What do you think happened to Spark's tummy?",
      context: "Spark just did something funny with pizza — a goofy comedy moment. This is purely for laughs and bonding.",
      transitionTo: "The next node introduces equal vs unequal parts with a visual applet.",
      fallback: "Ha, Spark's tummy is NOT happy! Silly robot. Okay, let's keep going!",
    },
  },
  // Node 7: Applet A3 — Cake Fractions
  {
    id: 'applet-a3',
    number: 7,
    type: 'applet',
    path: '/fractions-module-content/applets/A3. M2-Fraction Statement Cake Snapshot/index.html',
    title: 'Cake Fractions',
    duration: '3 min',
    preScript: "You've been cutting and comparing fractions — now let's learn the special math names for the top and bottom numbers! This cake activity will show you.",
    postQuestion: "What do we call the top number in a fraction?",
    contextInfo: "Cake-based vocabulary lesson. Teaches: equal parts (same size pieces), numerator (top number), denominator (bottom number).",
    correctnessFilter: "numerator",
    dynamicSlideTemplate: 'multiple-choice',
    dynamicSlideId: 'node-6-fraction-anatomy',
    wrapUp: "Numerator — now that's a powerful word! You're learning real math vocabulary!",
    scaffolding: {
      probe1: "In 3/4, the 3 is on top. It counts how many pieces you have. What's its special name?",
      probe2: "The top number has a fancy math name. It counts how many pieces you took. What could it be called?",
      hint: "It's the number that tells you how many parts. Think — the 'numer' in this word means 'number'!",
      reveal: "It's the numerator! The top number that counts your pieces. Great job trying!"
    },
    maxTurns: 4,
    minionMoment: {
      minionLine: "Ooh ooh! Why did the fraction go to the doctor? Because it was feeling... improper!",
      tutorLine: "Ha! That's terrible, Spark. But hey — we'll learn about improper fractions another time!",
    },
  },
  // Node 8: Checkpoint LO2 — Comparing & Naming Fractions
  {
    id: 'checkpoint-lo2',
    number: 8,
    type: 'checkpoint',
    path: '',
    title: 'Level Up: Fraction Expert!',
    duration: '2 min',
    preScript: "You've learned equal parts, compared fractions, and discovered the numerator! Let's see how much stuck.",
    postQuestion: "If you cut a pizza into 4 equal slices and eat 1, what fraction did you eat?",
    contextInfo: 'Checkpoint reviewing LO2: comparing fractions (1/4 vs 1/6), numerator concept.',
    isCheckpoint: true,
    checkpointLO: 'LO2: Comparing fractions and naming the numerator',
    checkpointId: 'lo2',
    maxTurns: 5,
    correctnessFilter: '1/4|one fourth|one quarter|one-fourth',
    scaffolding: {
      probe1: "You ate 1 slice. There are 4 total. How do we write that as a fraction?",
      probe2: "Remember, the piece you ate goes on top, total pieces on bottom.",
      hint: "It's 1 over 4. What fraction is that?",
      scaffold: "One slice out of four — put those words together and you've got it!",
      reveal: "It's 1/4 — one-fourth! You're doing amazing!"
    },
  },
  // Node 9: Slide 2 — What are Fractions? (preview for Video 2)
  {
    id: 'slide-2',
    number: 9,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-2-what-are-fractions.png',
    title: 'What are Fractions?',
    duration: '1 min',
    preScript: "Great job on that checkpoint! Now, here's something interesting — so far, all our fractions had a one on top, like one-fourth or one-sixth. But what if the top number is bigger? Hmm... take a look at this!",
    slideNarration: "See how these objects are cut into equal parts? Each part is a fraction. And here's the exciting part — sometimes you take MORE than one piece! Let's see what that looks like.",
    postQuestion: '',
    contextInfo: 'Preview slide for Video 2 - introduces cutting objects into equal parts.',
    correctnessFilter: '',
    scaffolding: {
      probe1: '',
      probe2: '',
      hint: '',
      scaffold: '',
      reveal: ''
    },
    maxTurns: 0,
    isQuestionSlide: false,
    minionMoment: {
      minionLine: "Oooh! I know this one! The numerator is the... um... the... hmm... I forgot!",
      tutorLine: "Almost, buddy! Let's watch this next part and it'll all make sense!",
    },
    microConversation: {
      type: 'recall',
      position: 'after_minion',
      prompt: "Quick — do you remember what we call the equal parts when we split something? Take a guess!",
      context: "Student has seen equal vs unequal parts in previous nodes. Testing if they remember the concept before a hands-on applet.",
      transitionTo: "The applet will let them build fractions by splitting shapes into equal parts.",
      fallback: "They're called equal parts! You'll be a pro at this after the next activity.",
    },
  },
  // Node 10: Video 2 — Bigger Fractions
  {
    id: 'video-2',
    number: 10,
    type: 'video',
    path: '/fractions-module-content/videos/video-2.mp4',
    youtubeId: 'pag3P1l3Tdk',
    title: 'Bigger Fractions',
    duration: '1.9 min',
    preScript: "You just saw objects cut into equal parts — with MORE than one piece colored in! This video shows how fractions get bigger. Watch what the top number does!",
    postQuestion: "Look at the fraction 2/4. What does the top number tell us?",
    contextInfo: "Advanced concept: numerators greater than 1. Examples: 2/4 (two quarters), 3/6 (three sixths).",
    correctnessFilter: "two pieces|2 pieces|two parts|2 parts|we have two|we have 2|it's two|it's 2|tells us two|tells us 2|means two|means 2",
    dynamicSlideTemplate: 'multiple-choice',
    dynamicSlideId: 'node-9-what-does-2-mean',
    wrapUp: "Two pieces — you just read a fraction with a bigger numerator. Nice!",
    scaffolding: {
      probe1: "Look at 2/4. The top number is 2. What does that 2 tell us?",
      probe2: "If the top number is 2, how many pieces do you have?",
      hint: "The answer is the same as the top number...",
      scaffold: "The top number is 2. How many pieces is that?",
      reveal: "Two pieces! The 2 on top means you have 2 pieces. Well done!"
    },
    maxTurns: 5,
    microConversation: {
      type: 'curiosity',
      position: 'after_prescript',
      prompt: "We're about to learn two big math words. Can you guess what the top number in a fraction might be called?",
      context: "Student is about to learn numerator and denominator. This prediction prompt builds anticipation.",
      transitionTo: "The slide will reveal that the top number is the numerator and the bottom is the denominator.",
      fallback: "Ooh, tough one! Let's find out what it's called!",
    },
  },
  // Node 11: Applet A4 — Advanced Practice
  {
    id: 'applet-a4',
    number: 11,
    type: 'applet',
    path: '/fractions-module-content/applets/A4.M2-Fraction Cut and Glue Practice 2/index.html',
    title: 'Advanced Practice',
    duration: '3 min',
    preScript: "In the video, you saw fractions like two-fourths and three-sixths — the top number got bigger! Now color pieces and write the fractions yourself.",
    postQuestion: "If you colored 3 pieces out of 5, what fraction is that?",
    contextInfo: "Advanced cutting practice. Kids create fractions like 2/5, 3/5. They should say both numerator and denominator.",
    correctnessFilter: "3/5|three fifths|three-fifths|3 over 5|three over five",
    dynamicSlideTemplate: 'fraction-builder',
    dynamicSlideId: 'node-10-build-fraction',
    wrapUp: "Three-fifths! You're building fractions like a pro now!",
    scaffolding: {
      probe1: "You colored 3 pieces. Total is 5 pieces. How do we write that?",
      probe2: "Remember: colored pieces go on TOP, total pieces go on BOTTOM. What do you get?",
      hint: "Count the colored pieces — that's your top number. Count ALL pieces — that's your bottom number.",
      scaffold: "Three on top, five on bottom. Say the fraction!",
      reveal: "It's 3/5! Three pieces out of five. Excellent effort!"
    },
    maxTurns: 5,
    minionMoment: {
      minionLine: "Hey Max! If I eat 3 out of 4 slices, I ate three-FORTHS right? Forths!",
      tutorLine: "So close! It's fourths — like the number four! Three-fourths. You'll get it!",
    },
  },
  // Node 12: Checkpoint LO3 — Building Bigger Fractions
  {
    id: 'checkpoint-lo3',
    number: 12,
    type: 'checkpoint',
    path: '',
    title: 'Level Up: Fraction Builder!',
    duration: '2 min',
    preScript: "You went from one-on-top fractions all the way to two-fourths and three-fifths — that's a huge leap! Let's see how much stuck with a quick check.",
    postQuestion: "If you colored 2 pieces out of 5, what fraction is that?",
    contextInfo: 'Checkpoint reviewing LO3: building fractions with numerators > 1, reading fractions like 2/5, 3/5.',
    isCheckpoint: true,
    checkpointLO: 'LO3: Building bigger fractions',
    checkpointId: 'lo3',
    maxTurns: 4,
    correctnessFilter: '2/5|two fifths|two-fifths|2 over 5|two over five',
    scaffolding: {
      probe1: "You colored 2 pieces. Total is 5. How do we write that?",
      probe2: "Colored pieces on top, total on bottom. What do you get?",
      hint: "Count the colored pieces — that's your top number. Count ALL pieces — that's your bottom number.",
      reveal: "It's 2/5 — two-fifths! You're building fractions like a pro!"
    },
  },
  // Node 13: Slide 3 — Math Vault: Fraction Definition
  {
    id: 'slide-3',
    number: 13,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-3-math-vault-fraction-definition.png',
    title: 'Math Vault: Fraction Definition',
    duration: '1 min',
    preScript: "You've been making fractions, comparing them, and learning their parts. Now it's time to unlock the official math definition — straight from the Math Vault!",
    slideNarration: "Here's the official definition: a fraction is a number that shows a part of a whole. The top number is the numerator — it counts the pieces you have. The bottom number is the denominator — it shows how many equal pieces there are in total!",
    postQuestion: '',
    contextInfo: 'Formal definition of fractions with numerator and denominator introduction.',
    correctnessFilter: '',
    scaffolding: {
      probe1: '',
      probe2: '',
      hint: '',
      scaffold: '',
      reveal: ''
    },
    maxTurns: 0,
    isQuestionSlide: false,
    microConversation: {
      type: 'recall',
      position: 'after_narration',
      prompt: "Those are some big math words! I bet you remember one — what's the top number of a fraction called?",
      context: "Student just heard the formal definition of fractions including numerator and denominator terms.",
      transitionTo: "The next slide visually breaks down numerator and denominator using 1/4 as an example.",
      fallback: "It's the numerator! That's a tough word — you'll remember it soon!",
    },
  },
  // Node 14: Slide 4 — Numerator and Denominator
  {
    id: 'slide-4',
    number: 14,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-4-numerator-and-denominator.png',
    title: 'Numerator and Denominator',
    duration: '1 min',
    preScript: "Let's take a closer look! Every fraction has two important parts — and you already know their names. Can you spot them?",
    slideNarration: "In one-fourth, the numerator is 1 — it shows how many parts we have. The denominator is 4 — it shows the total number of equal parts!",
    postQuestion: '',
    contextInfo: 'Visual breakdown of 1/4 showing numerator (top) and denominator (bottom).',
    correctnessFilter: '',
    scaffolding: {
      probe1: '',
      probe2: '',
      hint: '',
      scaffold: '',
      reveal: ''
    },
    maxTurns: 0,
    isQuestionSlide: false,
    minionMoment: {
      minionLine: "Max... I keep forgetting which one is the numerator and which is the denominator...",
      tutorLine: "Easy trick — D for Down, D for Denominator! The denominator is always on the bottom.",
    },
    microConversation: {
      type: 'personal',
      position: 'after_narration',
      prompt: "So 1/4 means 1 part out of 4. Can you think of something you'd split into 4 pieces?",
      context: "Student just saw 1/4 broken down visually. Connecting the abstract concept to their real world.",
      transitionTo: "The next node is a goofy moment with Spark, then a checkpoint quiz on identifying fractions.",
      fallback: "Pizza! Cake! Lots of yummy things come in four pieces. Let's keep going!",
    },
  },
  // Node 15: Checkpoint LO4 — Fraction Vocabulary
  {
    id: 'checkpoint-lo4',
    number: 15,
    type: 'checkpoint',
    path: '',
    title: 'Level Up: Vocabulary Master!',
    duration: '2 min',
    preScript: "Amazing progress! You've learned that the top number can be bigger than one, you know what numerator and denominator mean, and you've built fractions like three-fifths. Time for another quick check!",
    postQuestion: "In the fraction 3/5, what does the 3 tell us?",
    contextInfo: 'Checkpoint reviewing LO4: numerator/denominator vocabulary, reading fractions.',
    isCheckpoint: true,
    checkpointLO: 'LO4: Fraction vocabulary — numerator and denominator',
    checkpointId: 'lo4',
    maxTurns: 5,
    correctnessFilter: 'three pieces|3 pieces|three parts|3 parts|we have three|we have 3|it\'s three|it\'s 3|means three|means 3',
    scaffolding: {
      probe1: "The top number in a fraction counts something. What does the 3 count?",
      probe2: "Remember, the numerator tells us how many pieces we HAVE.",
      hint: "The 3 means we have three...",
      scaffold: "Three pieces! The numerator 3 means we have 3 pieces.",
      reveal: "The 3 tells us we have 3 pieces out of 5! Great thinking!"
    },
  },
  // Node 16: Slide 5 — Discover More Fractions (question slide)
  {
    id: 'slide-5',
    number: 16,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-5-discover-more-fractions.png',
    title: 'Discover More Fractions',
    duration: '2 min',
    preScript: "You just learned numerator and denominator — now use those words! Here's a pizza. Count the slices and build the fraction.",
    postQuestion: "If you have 2 slices out of 6 total slices, what fraction is that?",
    contextInfo: 'Quick check question - student should identify 2/6 as the fraction.',
    correctnessFilter: "2/6|two sixths|two-sixths|2 over 6|two over six",
    dynamicSlideTemplate: 'fraction-builder',
    dynamicSlideId: 'node-15-pizza-builder',
    wrapUp: "Two-sixths! You can read any fraction now — almost there!",
    scaffolding: {
      probe1: "You have 2 slices. There are 6 total. Which number goes on top?",
      probe2: "The pieces you have go on top. The total goes on bottom. What do you get?",
      hint: "Look at the pizza — count your slices, count all slices. Stack them!",
      scaffold: "Two on top, six on bottom. Say the fraction!",
      reveal: "It's 2/6! Two slices out of six. Great job!"
    },
    maxTurns: 5,
    isQuestionSlide: true
  },
  // Node 17: Video 3 — You Did It!
  {
    id: 'video-3',
    number: 17,
    type: 'video',
    path: '/fractions-module-content/videos/video-3.mp4',
    youtubeId: '6M7MIfeL7ak',
    title: 'You Did It!',
    duration: '30 sec',
    preScript: "You've sliced pizza, colored shapes, caught a sneaky math trap, and learned real math vocabulary — you've earned this! Watch this celebration video, then one final review question.",
    postQuestion: "Quick review! What's the bottom number called?",
    contextInfo: "Celebration video. End of session. Kid should feel accomplished and proud.",
    correctnessFilter: "denominator",
    dynamicSlideTemplate: 'multiple-choice',
    dynamicSlideId: 'node-16-bottom-number',
    wrapUp: "Denominator — you remembered! You really are a fraction expert!",
    scaffolding: {
      probe1: "In 3/4, the 4 is on the bottom. It shows total pieces. What's its name?",
      probe2: "The bottom number tells you how many total pieces there are. What's the math word for that?",
      hint: "Remember Spark's trick? D for Down, D for Denominator! What's the name for the bottom number?",
      reveal: "It's the denominator! The bottom number showing total pieces. Amazing work today!"
    },
    maxTurns: 4,
    minionMoment: {
      minionLine: "Can I get a fraction of a vacation after all this math? Like... one-seventh of a beach day?",
      tutorLine: "Ha! I think you've earned a WHOLE vacation, not just a fraction of one!",
    },
  },
  // Node 18: Slide 6 — Math Trap: Find the Error (question slide)
  {
    id: 'slide-6',
    number: 18,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-6-math-trap-find-the-error.png',
    title: 'Math Trap: Find the Error',
    duration: '2 min',
    preScript: "Time to put on your detective hat! I'm going to show you two fraction diagrams, but one of them has a mistake hidden in it. Can you figure out which one is wrong?",
    postQuestion: "Look at the two bar diagrams. One shows 2/4 and one shows 2/6. Which diagram is wrong?",
    contextInfo: 'Diagnostic slide - student should identify the incorrect fraction diagram.',
    correctnessFilter: "2/6|two sixths|second|bottom|six",
    dynamicSlideTemplate: 'tap-to-select',
    dynamicSlideId: 'node-17-math-detective',
    wrapUp: "You spotted the error! Nothing gets past you. One more to go!",
    scaffolding: {
      probe1: "Count the shaded parts in each diagram. Do they match the fractions written?",
      probe2: "Look carefully - does 2/6 really have 2 out of 6 parts shaded?",
      hint: "Check the bottom diagram. How many total parts does it show?",
      scaffold: "The 2/6 diagram should have 6 total parts. Does it?",
      reveal: "The 2/6 diagram is wrong! It doesn't show 6 equal parts. Good thinking!"
    },
    maxTurns: 5,
    isQuestionSlide: true
  },
  // Node 19: Slide 7 — Snapshot: More Parts
  {
    id: 'slide-7',
    number: 19,
    type: 'slide',
    path: '',
    slideUrl: '/fractions-module-content/slides/slide-7-snapshot-more-parts.png',
    title: 'Snapshot: More Parts',
    duration: '1 min',
    preScript: "You spotted that error like a real math detective! Now let's take one final look at everything you've learned about fractions.",
    slideNarration: "Remember, fractions can show multiple parts! Like 2/5, 3/5, or 4/6. You're a fraction expert now!",
    postQuestion: '',
    contextInfo: 'Final summary slide - fractions can have numerators greater than 1.',
    correctnessFilter: '',
    scaffolding: {
      probe1: '',
      probe2: '',
      hint: '',
      scaffold: '',
      reveal: ''
    },
    maxTurns: 0,
    isQuestionSlide: false,
    minionMoment: {
      minionLine: "WE DID IT! WE DID IT! We're fraction masters! ...Right, Max?",
      tutorLine: "Almost there, Spark! One last checkpoint and then you're officially a Fraction Master!",
    },
    microConversation: {
      type: 'curiosity',
      position: 'after_narration',
      prompt: "Here's a tricky one — which do you think is bigger, 1/2 or 1/4? What's your gut feeling?",
      context: "Student is being introduced to comparing fractions. This is a prediction before they learn the visual method.",
      transitionTo: "The next interactive applet will let them visually compare fraction sizes.",
      fallback: "That's a brain-tickler! Let's find out together in the next activity!",
    },
  },
  // Node 20: Checkpoint LO5 — Fraction Master
  {
    id: 'checkpoint-lo5',
    number: 20,
    type: 'checkpoint',
    path: '',
    title: 'Level Up: Fraction Master!',
    duration: '2 min',
    preScript: "What a journey! You started by sharing cake, learned about equal parts, discovered numerators and denominators, and even caught a sneaky math trap! One last challenge — and then you're officially a Fraction Master!",
    postQuestion: "If you have a chocolate bar cut into 6 pieces and you eat 2, what fraction did you eat?",
    contextInfo: 'Final checkpoint reviewing LO5: applying fraction knowledge, identifying fractions, spotting errors.',
    isCheckpoint: true,
    checkpointLO: 'LO5: Applying fraction knowledge',
    checkpointId: 'lo5',
    maxTurns: 5,
    correctnessFilter: '2/6|two sixths|two-sixths|2 over 6',
    scaffolding: {
      probe1: "You ate 2 pieces. Total is 6. What fraction is that?",
      probe2: "Pieces you ate go on top. Total pieces on bottom.",
      hint: "Pieces you ate go on top. Total pieces go on bottom. Say it!",
      scaffold: "Two pieces out of six — put that together as a fraction!",
      reveal: "It's 2/6 — two-sixths! You're a fraction master!"
    },
  },
];
